# Generated by Django 4.1.5 on 2023-04-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='my_coin_burn_day',
            new_name='average_balance',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='burn_amount',
            new_name='number_of_addresses',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='my_coin_burn_month',
            new_name='percent_of_supply',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='my_coin_burn_week',
            new_name='sum_of_balances',
        ),
        migrations.RemoveField(
            model_name='data',
            name='circulating_supply',
        ),
        migrations.RemoveField(
            model_name='data',
            name='my_coin_holders',
        ),
        migrations.RemoveField(
            model_name='data',
            name='my_coin_holders_day',
        ),
        migrations.RemoveField(
            model_name='data',
            name='price_btc',
        ),
        migrations.RemoveField(
            model_name='data',
            name='price_eth',
        ),
        migrations.RemoveField(
            model_name='data',
            name='price_my_coin',
        ),
        migrations.AddField(
            model_name='data',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
