# Generated by Django 4.1.5 on 2023-05-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_my_coin_burn_day_data_average_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('file_name', models.TextField(blank=True, null=True)),
                ('download_url', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
